In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Matrix Multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [ ]:
#Eigen Decomposition
A=np.array([[4,2],[1,3]])
eigenvalues,eigenvector=np.linalg.eig(A)
eigenvalues,eigenvector

(array([5., 2.]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

In [ ]:
#Singular Value Decomposition
A = np.array([[3, 2, 2], [2, 3, -2]])
U, S, V = np.linalg.svd(A)
U, S, V


(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([5., 3.]),
 array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
        [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]]))

In [ ]:
#Determinant Calculation
A = np.array([[6, 1], [2, 3]])
det=np.linalg.det(A)
det


15.999999999999998

In [ ]:
#Norm Calculation
v=np.array([3,4])
l1=np.linalg.norm(v,ord=1)
l2=np.linalg.norm(v)
print(v)
print(l1)
print(l2)

[3 4]
7.0
5.0
